name: model deployment

env:
    registered_model_name: train_model
on:
    workflow_dispatch:  

jobs:
  deployment-job:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Get model version
      id: get_version
      run: |
          VERSION=$(az ml model list --name $registered_model_name --resource-group ml_rg --workspace-name trainworkspace | jq -r '.[0].version')
          echo "Version is $VERSION"
          echo "::set-output name=version::$VERSION"  
    # Commenting out as endpoint creation is only needed during the first run
    # - name: create-endpoint
    #   run: az ml online-endpoint create --name train-deployment --resource-group ml_rg --workspace-name trainworkspace
    - name: update deploy yaml
      run: | 
        python model/update_deploy_yaml.py --model_name azureml:$registered_model_name:${{ steps.get_version.outputs.version }}
      working-directory: src
    - name: deployment-step
      run: az ml online-deployment create -f deploy.yml --all-traffic --resource-group ml_rg --workspace-name trainworkspace
    #   run: az ml online-deployment update -f deploy.yml 
      #--all-traffic # First time it'll be az ml ... create --all-traffic
      working-directory: src/model